import React, { type FC } from 'react';
import { Outlet } from 'react-router-dom';

export const Component: FC = () => <Outlet />;

Component.displayName = 'AdminRoute';

/*
<Section>
      <div className="flex flex-col gap-2 bg-light-surface-dark">
        <Button
          variant="plain"
          color="default"
        >
          Button
        </Button>
        <Button
          variant="plain"
          color="primary"
        >
          Button
        </Button>
        <Button
          variant="plain"
          color="secondary"
        >
          Button
        </Button>
        <Button
          variant="plain"
          color="success"
        >
          Button
        </Button>
        <Button
          variant="plain"
          color="warning"
        >
          Button
        </Button>
        <Button
          variant="plain"
          color="error"
        >
          Button
        </Button>
      </div>
      <div className="flex flex-col gap-2">
        <Button
          variant="text"
          color="default"
        >
          Button
        </Button>
        <Button
          variant="text"
          color="primary"
        >
          Button
        </Button>
        <Button
          variant="text"
          color="secondary"
        >
          Button
        </Button>
        <Button
          variant="text"
          color="success"
        >
          Button
        </Button>
        <Button
          variant="text"
          color="warning"
        >
          Button
        </Button>
        <Button
          variant="text"
          color="error"
        >
          Button
        </Button>
      </div>
      <div className="flex flex-col gap-2">
        <Button
          variant="soft"
          color="default"
        >
          Button
        </Button>
        <Button
          variant="soft"
          color="primary"
        >
          Button
        </Button>
        <Button
          variant="soft"
          color="secondary"
        >
          Button
        </Button>
        <Button
          variant="soft"
          color="success"
        >
          Button
        </Button>
        <Button
          variant="soft"
          color="warning"
        >
          Button
        </Button>
        <Button
          variant="soft"
          color="error"
        >
          Button
        </Button>
      </div>
      <div className="flex flex-col gap-2">
        <Button
          variant="solid"
          color="default"
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="primary"
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="secondary"
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="success"
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="warning"
        >
          Button
        </Button>
        <Button
          variant="solid"
          color="error"
        >
          Button
        </Button>
      </div>
      <div className="flex flex-col gap-2">
        <Button
          variant="outlined"
          color="default"
        >
          Button
        </Button>
        <Button
          variant="outlined"
          color="primary"
        >
          Button
        </Button>
        <Button
          variant="outlined"
          color="secondary"
        >
          Button
        </Button>
        <Button
          variant="outlined"
          color="success"
        >
          Button
        </Button>
        <Button
          variant="outlined"
          color="warning"
        >
          Button
        </Button>
        <Button
          variant="outlined"
          color="error"
        >
          Button
        </Button>
      </div>
    </Section> */
